apiVersion: apps/v1
kind: Deployment
metadata:
  name: iti
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: cont1
          image: nginx 
          ports: 
            - name: http
              containerPort: 80
              protocol: tcp   
           
         